### ISSUE TITLE
ECX Follow-up. Urgent Attention Required

### ISSUE THREAD

**Issue by KeneNwogu** [HydesSyde/Node-Express.js-#1]
Hello, you submitted this repository as your favourite project. It's great work, but you didn't send your contact details on the form. I would love to talk about the project. If you are still up for it, can you send your email as a comment to this issue

Regards,
Kenechukwu.
Development Lead, ECX 5.0.

**Comment by HydesSyde** [comment]
eshimi090@gmail.com

**Comment by KeneNwogu** [comment]
Thank you very much. Looking forward to speaking with you.
